export const applianceFixture = {
  entry_id: "plant",
  revision: 1,
  appliances: [
    {
      id: "washer",
      name: "Washing machine",
      revision: 1,
      status: "running",
      program: "Eco 40",
      program_source: "active",
      observation: {
        power_w: 420,
        remaining_minutes: 35,
        remaining_source: "reported",
        expected_end: "2026-09-27T10:35:00+02:00",
        cycle_energy_wh: 480,
        energy_source: "energy_counter",
        complete: true,
        started_at: "2026-09-27T09:00:00+02:00",
      },
      planning: {
        energy_wh: 600,
        energy_source: "program_profile",
        duration_minutes: 110,
        duration_source: "program_profile",
      },
      learning: {
        status: "learned",
        sample_count: 3,
        last_learned_at: "2026-09-26T11:00:00+02:00",
        device_profile: {
          energy_wh: 700,
          energy_min_wh: 500,
          energy_max_wh: 1100,
          count: 4,
          last_learned_at: "2026-09-26T11:00:00+02:00",
        },
        profiles: [
          {
            program: "Eco 40",
            energy_wh: 600,
            duration_h: 110 / 60,
            energy_min_wh: 550,
            energy_max_wh: 650,
            duration_min_h: 1.5,
            duration_max_h: 2,
            count: 3,
            selected: true,
            last_learned_at: "2026-09-26T11:00:00+02:00",
          },
          {
            program: "Quick",
            energy_wh: 300,
            duration_h: 0.5,
            energy_min_wh: 300,
            energy_max_wh: 300,
            duration_min_h: 0.5,
            duration_max_h: 0.5,
            count: 1,
            last_learned_at: "2026-09-25T11:00:00+02:00",
          },
        ],
        history: [
          {
            program: "Eco 40",
            started_at: "2026-09-26T09:00:00+02:00",
            ended_at: "2026-09-26T11:00:00+02:00",
            duration_h: 2,
            energy_wh: 600,
            measurement_source: "energy_counter",
            complete: true,
            accepted: true,
            reasons: [],
            warnings: ["counter_reset"],
          },
          {
            program: "Quick",
            started_at: "2026-09-25T09:00:00+02:00",
            ended_at: "2026-09-25T09:15:00+02:00",
            duration_h: 0.25,
            energy_wh: 200,
            measurement_source: "integrated_power",
            complete: false,
            accepted: false,
            reasons: ["measurement_gap"],
            warnings: [],
          },
        ],
      },
      recommendation: { allowed: false, reasons: ["extra_grid_import"] },
      sources: [
        {
          kind: "power",
          entity_id: "sensor.washer_power",
          state: "420",
          available: true,
          last_reported: "2026-09-27T10:00:00+02:00",
        },
      ],
    },
    {
      id: "dryer",
      name: "Dryer",
      revision: 1,
      status: "idle",
      program: null,
      program_source: null,
      observation: {
        power_w: null,
        remaining_minutes: null,
        expected_end: null,
        cycle_energy_wh: null,
        complete: false,
      },
      planning: {
        energy_wh: 1000,
        energy_source: "configured",
        duration_minutes: 90,
        duration_source: "configured",
      },
      learning: {
        status: "no_data",
        sample_count: 0,
        profiles: [],
        history: [],
      },
      recommendation: { allowed: null, reasons: ["no_valid_plan"] },
      sources: [],
    },
  ],
};
