import { build } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";
const output =
  "custom_components/battery_manager/frontend/battery-manager-forecast-card.js";
const result = await build({
  entryPoints: ["frontend/index.js"],
  bundle: true,
  format: "esm",
  target: "es2022",
  write: false,
  banner: { js: "// Generated by npm run build; edit frontend/ sources." },
});
const text = result.outputFiles[0].text;
if (process.argv.includes("--check")) {
  if ((await readFile(output, "utf8")) !== text)
    throw new Error("Frontend bundle is stale; run npm run build");
} else await writeFile(output, text);
