name: Release

on:
  release:
    types: [published]

jobs:
  validate:
    runs-on: "ubuntu-latest"
    name: Validate for release
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
        
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
          
      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"
        
  release:
    runs-on: "ubuntu-latest"
    needs: validate
    name: Update release info
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
        
      - name: Update manifest version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" custom_components/battery_manager/manifest.json
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add custom_components/battery_manager/manifest.json
          git diff --staged --quiet || git commit -m "Update version to ${GITHUB_REF#refs/tags/v}"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
