name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  validate-hacs:
    runs-on: "ubuntu-latest"
    name: HACS Validation
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
        
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
          ignore: "topics description brands"
          
  validate-hassfest:
    runs-on: "ubuntu-latest"
    name: Hassfest Validation
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
        
      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"
        
  validate-code:
    runs-on: "ubuntu-latest"
    name: Code Quality
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
        
      - name: Set up Python
        uses: "actions/setup-python@v4"
        with:
          python-version: "3.11"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort
          
      - name: Lint with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 custom_components --count --select=E9,F63,F7,F82 --show-source --statistics
          # Exit-zero treats all errors as warnings
          flake8 custom_components --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
          
      - name: Check code formatting with black
        run: |
          black --check custom_components
          
      - name: Check import sorting with isort
        run: |
          isort --check-only custom_components
